import { ChatDetalles } from "@/components/ChatDetalles";
import { Container } from "@/components/Container";
import { ListChats } from "@/components/ListChats";
import { ListMessage } from "@/components/ListMessage";
import { Message } from "@/components/Message";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ChatDetalles</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <ChatDetalles/>

       
        


      </Container>
    </>
  )
}