import { Container } from "@/components/Container";
import { UserInfo } from "@/components/UserInfo";
import Head from "next/head";
import { History } from "@/components/History"
export default function Home() {
    return (
      <>
        <Head>
          <title>History</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Container>
          <History
          img="/images/history1.png"
          
          
          />
        
        </Container>
      </>
    )
  }