import { CircleImages } from "@/components/CircleImages";
import { Container } from "@/components/Container";
import { ContentProfile } from "@/components/ContentProfile";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>

        <ContentProfile />

      </Container>

    </>
  )
}
