import { Container } from '@/components/Container'
import { FormRegister } from '@/components/FormRegister'
import { Input } from '@/components/Input'
import { LoadLoginRegister } from '@/components/LoadLoginRegister'
import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Container>
                <FormRegister/>
                
            </Container>






        </>
    )
}
